name: venv
channels:
  - defaults
dependencies:
  - numpy
  - python=3.8
  - pandas
  - nest-asyncio
  - openssl
  - pywin32
  - tornado
  - pure_eval
  - pip
  - debugpy
  - vc
  - python-dateutil
  - jupyter_client
  - asttokens
  - sqlite
  - colorama
  - pickleshare
  - libsodium
  - psutil
  - vs2015_runtime
  - pyzmq
  - executing
  - wheel
  - stack_data
  - packaging
  - certifi
  - entrypoints
  - jupyter_core
  - backcall
  - pygments
  - wincertstore
  - prompt-toolkit
  - matplotlib-inline
  - decorator
  - jedi
  - wcwidth
  - six
  - pyparsing
  - traitlets
  - setuptools
  - ipython
  - parso
  - zeromq
  - ca-certificates
  - ipykernel
  - black
