version: 1
disable_existing_loggers: False
formatters:
  simple:
    # "%(asctime)s | [%(filename)s][%(levelname)s]: %(message)s"
    format: "%(asctime)s | [%(levelname)5s][%(filename)20s] | %(message)s"
  detail:
    format: "%(asctime)s.%(msecs)03d | [%(levelname)5s][%(module)s - %(funcName)s] | %(message)s"
handlers:
  debug_console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: detail
    stream: ext://sys.stdout

  info_console: # handles info
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detail
    filename: ./data/logs/debug.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: ./data/logs/info.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
  warning_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: simple
    filename: ./data/logs/warning.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: ./data/logs/error.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
loggers:
  All:
    level: DEBUG
    handlers:
      [debug_console, debug_file_handler, info_file_handler, error_file_handler]
    propagate: yes

  Dev:
    level: INFO
    handlers:
      [info_console, debug_file_handler, info_file_handler, error_file_handler]
    propagate: yes

  Prod:
    level: WARNING
    handlers: [warning_file_handler, error_file_handler]
    propagate: yes

  root:
    level: DEBUG
    handlers:
      [debug_console, info_file_handler, debug_file_handler, error_file_handler]
